"""Explicit ScopeLock workflow and commercial state values."""

from enum import StrEnum


class ProjectLifecycleStatus(StrEnum):
    NEW = "NEW"
    ANALYZING_REQUIREMENTS = "ANALYZING_REQUIREMENTS"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    AWAITING_USER_REVIEW = "AWAITING_USER_REVIEW"
    REJECTED = "REJECTED"
    PROPOSAL_SENT = "PROPOSAL_SENT"
    NEGOTIATING = "NEGOTIATING"
    ACCEPTED = "ACCEPTED"
    ACTIVE_PROJECT = "ACTIVE_PROJECT"
    COMPLETED = "COMPLETED"


class ArtifactType(StrEnum):
    PROPOSAL = "PROPOSAL"
    PROPOSAL_REVISION = "PROPOSAL_REVISION"
    CHANGE_ORDER = "CHANGE_ORDER"


class ArtifactStatus(StrEnum):
    DRAFT = "DRAFT"
    AWAITING_USER_REVIEW = "AWAITING_USER_REVIEW"
    APPROVED = "APPROVED"
    SENDING = "SENDING"
    SENT = "SENT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    STALE = "STALE"
    GENERATION_FAILED = "GENERATION_FAILED"
    SEND_FAILED = "SEND_FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class ProposalStatus(StrEnum):
    DRAFT = "DRAFT"
    AWAITING_USER_REVIEW = "AWAITING_USER_REVIEW"
    APPROVED = "APPROVED"
    SENDING = "SENDING"
    SENT = "SENT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    STALE = "STALE"
    GENERATION_FAILED = "GENERATION_FAILED"
    SEND_FAILED = "SEND_FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class ChangeOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    AWAITING_USER_REVIEW = "AWAITING_USER_REVIEW"
    APPROVED = "APPROVED"
    SENDING = "SENDING"
    SENT = "SENT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    STALE = "STALE"
    GENERATION_FAILED = "GENERATION_FAILED"
    SEND_FAILED = "SEND_FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class ScopeVersionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    SUPERSEDED = "SUPERSEDED"


class ScopeEventClassification(StrEnum):
    NO_CHANGE = "NO_CHANGE"
    CLARIFICATION = "CLARIFICATION"
    AMBIGUOUS = "AMBIGUOUS"
    EXPANSION = "EXPANSION"
    REDUCTION = "REDUCTION"
    REPLACEMENT = "REPLACEMENT"
    CLOSURE = "CLOSURE"


class ScopeEventStatus(StrEnum):
    DETECTED = "DETECTED"
    CLASSIFIED = "CLASSIFIED"
    RECORDED = "RECORDED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    BUFFERED = "BUFFERED"
    CONSOLIDATED = "CONSOLIDATED"
    AWAITING_USER_REVIEW = "AWAITING_USER_REVIEW"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    SENT = "SENT"
    CLIENT_ACCEPTED = "CLIENT_ACCEPTED"
    APPLIED = "APPLIED"


class ApprovalStatus(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"


class SendIntentStatus(StrEnum):
    CREATED = "CREATED"


class ConfidenceBand(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ScopeAnalysisStatus(StrEnum):
    READY = "READY"
    REVIEW_RECOMMENDED = "REVIEW_RECOMMENDED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
