import type { DashboardSnapshot, InboxMessageDetail, ProjectDetailSnapshot } from "@/lib/types";

const now = "2026-08-30T07:17:46Z";

export const demoDashboard: DashboardSnapshot = {
  generated_at: now,
  projects: [
    {
      id: "demo-project-aurora",
      client_name: "Aurora Operations",
      client_email: "client@example.com",
      gmail_thread_id: "demo-thread-01",
      title: "Customer request intake automation",
      lifecycle_status: "AWAITING_USER_REVIEW",
      active_scope_version_id: "demo-scope-v1",
      active_proposal_id: "demo-artifact-v1",
      scope_buffer_id: null,
      current_price_usd: 5650,
      current_timeline_days: 5,
      correlation_id: "demo-correlation-01",
      created_at: "2026-08-30T06:58:00Z",
      updated_at: now,
    },
    {
      id: "demo-project-northstar",
      client_name: "Northstar Services",
      client_email: "ops@example.com",
      gmail_thread_id: "demo-thread-02",
      title: "Operations dashboard rollout",
      lifecycle_status: "AWAITING_USER_REVIEW",
      baseline_scope_version_id: "demo-scope-accepted",
      active_scope_version_id: "demo-scope-accepted",
      active_proposal_id: "demo-change-order-1",
      scope_buffer_id: null,
      current_price_usd: 4750,
      current_timeline_days: 5,
      correlation_id: "demo-correlation-02",
      created_at: "2026-08-29T03:00:00Z",
      updated_at: "2026-08-30T06:45:00Z",
    },
  ],
  artifacts: [
    {
      id: "demo-artifact-v1",
      project_id: "demo-project-aurora",
      artifact_type: "PROPOSAL",
      version_number: 1,
      proposed_scope_version_id: "demo-scope-v1",
      status: "AWAITING_USER_REVIEW",
      sop_version: "jvl-demo-v1",
      calculation_inputs: [
        { module_key: "core_workflow_automation", quantity: 1 },
        { module_key: "email_intake", quantity: 1 },
        { module_key: "operations_dashboard", quantity: 1 },
        { module_key: "email_notifications", quantity: 1 },
      ],
      pricing_result: {
        currency: "USD",
        sop_version: "jvl-demo-v1",
        total_usd: 5650,
        line_items: [
          {
            module_key: "core_workflow_automation",
            quantity: 1,
            unit_rule: "fixed",
            unit_amount_usd: 4000,
            subtotal_usd: 4000,
            currency: "USD",
            sop_version: "jvl-demo-v1",
          },
          {
            module_key: "email_intake",
            quantity: 1,
            unit_rule: "fixed",
            unit_amount_usd: 500,
            subtotal_usd: 500,
            currency: "USD",
            sop_version: "jvl-demo-v1",
          },
          {
            module_key: "operations_dashboard",
            quantity: 1,
            unit_rule: "fixed",
            unit_amount_usd: 750,
            subtotal_usd: 750,
            currency: "USD",
            sop_version: "jvl-demo-v1",
          },
          {
            module_key: "email_notifications",
            quantity: 1,
            unit_rule: "fixed",
            unit_amount_usd: 400,
            subtotal_usd: 400,
            currency: "USD",
            sop_version: "jvl-demo-v1",
          },
        ],
      },
      timeline_result: { total_days: 5, sop_version: "jvl-demo-v1" },
      checksum: "1".repeat(64),
      created_at: now,
    },
    {
      id: "demo-change-order-1",
      project_id: "demo-project-northstar",
      artifact_type: "CHANGE_ORDER",
      version_number: 2,
      change_order_number: 1,
      baseline_scope_version_id: "demo-scope-accepted",
      proposed_scope_version_id: "demo-scope-change",
      source_buffer_id: "demo-buffer-1",
      status: "AWAITING_USER_REVIEW",
      sop_version: "jvl-demo-v1",
      calculation_inputs: [
        { module_key: "core_workflow_automation", quantity: 1 },
        { module_key: "operations_dashboard", quantity: 1 },
        { module_key: "line_notifications", quantity: 1 },
        { module_key: "line_approval", quantity: 1 },
      ],
      pricing_result: {
        currency: "USD",
        sop_version: "jvl-demo-v1",
        total_usd: 6250,
        line_items: [
          {
            module_key: "core_workflow_automation",
            quantity: 1,
            unit_rule: "fixed",
            unit_amount_usd: 4000,
            subtotal_usd: 4000,
            currency: "USD",
            sop_version: "jvl-demo-v1",
          },
          {
            module_key: "operations_dashboard",
            quantity: 1,
            unit_rule: "fixed",
            unit_amount_usd: 750,
            subtotal_usd: 750,
            currency: "USD",
            sop_version: "jvl-demo-v1",
          },
          {
            module_key: "line_notifications",
            quantity: 1,
            unit_rule: "fixed",
            unit_amount_usd: 750,
            subtotal_usd: 750,
            currency: "USD",
            sop_version: "jvl-demo-v1",
          },
          {
            module_key: "line_approval",
            quantity: 1,
            unit_rule: "fixed",
            unit_amount_usd: 750,
            subtotal_usd: 750,
            currency: "USD",
            sop_version: "jvl-demo-v1",
          },
        ],
      },
      timeline_result: { total_days: 10, sop_version: "jvl-demo-v1" },
      checksum: "2".repeat(64),
      created_at: "2026-08-30T06:45:00Z",
    },
  ],
  scope_events: [
    {
      id: "demo-event-expansion",
      project_id: "demo-project-northstar",
      gmail_message_id: "demo-gmail-change",
      baseline_scope_version_id: "demo-scope-accepted",
      classification: "EXPANSION",
      status: "AWAITING_USER_REVIEW",
      description: "Managers can approve requests from WhatsApp and receive WhatsApp alerts.",
      additions: [
        { module_key: "line_notifications", quantity: 1 },
        { module_key: "line_approval", quantity: 1 },
      ],
      reductions: [],
      replacements: [],
      evidence: [
        {
          source_type: "gmail",
          source_id: "demo-gmail-change",
        quote_or_rule: "Can managers also approve requests from WhatsApp and receive WhatsApp alerts?",
        },
      ],
      price_delta_usd: 1500,
      timeline_delta_days: 5,
      review_required: false,
      correlation_id: "demo-correlation-02",
      created_at: "2026-08-30T06:39:00Z",
    },
    {
      id: "demo-event-no-change",
      project_id: "demo-project-northstar",
      gmail_message_id: "demo-gmail-title",
      baseline_scope_version_id: "demo-scope-accepted",
      classification: "NO_CHANGE",
      status: "RECORDED",
      description: "Rename the dashboard title to Operations Overview.",
      additions: [],
      reductions: [],
      replacements: [],
      evidence: [],
      price_delta_usd: 0,
      timeline_delta_days: 0,
      review_required: false,
      correlation_id: "demo-correlation-03",
      created_at: "2026-08-30T06:22:00Z",
    },
  ],
  scope_buffers: [
    {
      id: "demo-buffer-1",
      project_id: "demo-project-northstar",
      baseline_scope_version_id: "demo-scope-accepted",
      event_ids: ["demo-event-expansion"],
      additions: [
        { module_key: "line_notifications", quantity: 1 },
        { module_key: "line_approval", quantity: 1 },
      ],
      reductions: [],
      replacements: [],
      proposed_module_selections: [
        { module_key: "core_workflow_automation", quantity: 1 },
        { module_key: "operations_dashboard", quantity: 1 },
        { module_key: "line_notifications", quantity: 1 },
        { module_key: "line_approval", quantity: 1 },
      ],
      net_price_delta_usd: 1500,
      net_timeline_delta_days: 5,
      status: "FINALIZED",
      last_client_message_at: "2026-08-30T06:39:00Z",
      quiet_window_minutes: 20,
      quiet_window_expires_at: "2026-08-30T06:59:00Z",
      finalized_at: "2026-08-30T06:45:00Z",
      finalization_reason: "SEMANTIC_CLOSURE",
      correlation_id: "demo-correlation-02",
      created_at: "2026-08-30T06:39:00Z",
      updated_at: "2026-08-30T06:45:00Z",
    },
  ],
  agent_runs: [
    {
      id: "demo-agent-run-1",
      correlation_id: "demo-correlation-01",
      project_id: "demo-project-aurora",
      agent_name: "requirement_analyzer",
      model: "gemini-3.5-flash",
      prompt_version: "requirement_analyzer_v5",
      status: "COMPLETED",
      started_at: "2026-08-30T07:16:55Z",
      completed_at: "2026-08-30T07:17:02Z",
      tool_count: 2,
      retryable: false,
    },
    {
      id: "demo-agent-run-2",
      correlation_id: "demo-correlation-02",
      project_id: "demo-project-northstar",
      agent_name: "scope_analyzer",
      model: "gemini-3.5-flash",
      prompt_version: "scope_analyzer_v4",
      status: "COMPLETED",
      started_at: "2026-08-30T07:17:35Z",
      completed_at: "2026-08-30T07:17:45Z",
      tool_count: 6,
      retryable: false,
    },
  ],
  inbox_messages: [
    {
      id: "demo-inbound-aurora",
      project_id: "demo-project-aurora",
      sender_name: "Aurora Operations",
      sender_email: "client@example.com",
      subject: "Automation project requirements",
      received_at: "2026-08-30T06:58:00Z",
      direction: "INBOUND",
      attachment_count: 0,
    },
    {
      id: "demo-inbound-northstar",
      project_id: "demo-project-northstar",
      sender_name: "Northstar Services",
      sender_email: "ops@example.com",
      subject: "Question about manager alerts",
      received_at: "2026-08-30T06:39:00Z",
      direction: "INBOUND",
      attachment_count: 0,
    },
    {
      id: "demo-inbound-northstar-closure",
      project_id: "demo-project-northstar",
      sender_name: "Northstar Services",
      sender_email: "ops@example.com",
      subject: "Re: Question about manager alerts",
      received_at: "2026-08-30T06:45:00Z",
      direction: "INBOUND",
      attachment_count: 0,
    },
  ],
  gmail_watch: {
    mailbox: "demo-inbox@example.com",
    expiration: "2026-09-05T07:17:46Z",
    created_at: "2026-08-30T06:58:00Z",
  },
  readiness: {
    status: "PASS",
    verified_at: now,
    model: "gemini-3.5-flash",
    prompt_versions: ["requirement_analyzer_v5", "scope_analyzer_v4"],
    checks: [
      {
        key: "deterministic",
        label: "Deterministic contract and workflow tests",
        passed: 216,
        expected: 216,
      },
      {
        key: "requirement_eval",
        label: "Requirement Analyzer reviewed cases",
        passed: 12,
        expected: 12,
      },
      {
        key: "scope_eval",
        label: "Scope Analyzer reviewed cases",
        passed: 35,
        expected: 35,
      },
      {
        key: "trajectory_eval",
        label: "Approval-safe tool trajectories",
        passed: 2,
        expected: 2,
      },
      {
        key: "repeatability",
        label: "Focused live-model repeatability",
        passed: 18,
        expected: 18,
      },
    ],
    note: "Reviewed demo data. Hosted event delivery remains a separate activation gate.",
  },
  warnings: [],
};

export const demoInboxMessageDetails: Record<string, InboxMessageDetail> = {
  "demo-inbound-aurora": {
    ...demoDashboard.inbox_messages[0],
    body: "Hello JVL Team,\n\nWe would like an automated customer-request intake workflow that captures email requests, tracks them in an operations dashboard, and sends confirmation notifications. Please share the recommended scope, delivery timeline, and investment.\n\nBest,\nAurora Operations",
    body_format: "PLAIN",
    attachments: [],
  },
  "demo-inbound-northstar": {
    ...demoDashboard.inbox_messages[1],
    body: "Hi team,\n\nCan managers also approve requests from WhatsApp and receive WhatsApp alerts? Please let us know the impact on price and delivery.\n\nThanks,\nNorthstar Services",
    body_format: "PLAIN",
    attachments: [],
  },
  "demo-inbound-northstar-closure": {
    ...demoDashboard.inbox_messages[2],
    body: "That covers the additional requirements. Please prepare the updated change order for review.",
    body_format: "PLAIN",
    attachments: [],
  },
};

const auroraProject = demoDashboard.projects[0];
const northstarProject = demoDashboard.projects[1];
const auroraArtifact = demoDashboard.artifacts[0];
const northstarArtifact = demoDashboard.artifacts[1];

export const demoProjectDetails: Record<string, ProjectDetailSnapshot> = {
  [auroraProject.id]: {
    generated_at: now,
    project: auroraProject,
    scope_versions: [
      {
        id: "demo-scope-v1",
        project_id: auroraProject.id,
        version_number: 1,
        status: "PROPOSED",
        requirements: [
          { requirement_id: "REQ-01", category: "Workflow", description: "Classify incoming customer requests and store structured records.", normalized_key: "customer_request_automation" },
          { requirement_id: "REQ-02", category: "Intake", description: "Read requests from one shared Gmail inbox.", normalized_key: "gmail_intake" },
          { requirement_id: "REQ-03", category: "Dashboard", description: "Show request status in a simple operations dashboard.", normalized_key: "operations_dashboard" },
          { requirement_id: "REQ-04", category: "Notification", description: "Email the team when a request needs manual review.", normalized_key: "email_notifications" },
        ],
        module_selections: auroraArtifact.calculation_inputs,
        assumptions: ["One shared Gmail mailbox is the only intake channel."],
        exclusions: ["Multi-mailbox routing and advanced BI modelling are excluded."],
        pricing_result: auroraArtifact.pricing_result,
        timeline_result: auroraArtifact.timeline_result,
        total_price_usd: auroraArtifact.pricing_result.total_usd,
        timeline_days: auroraArtifact.timeline_result.total_days,
        currency: "USD",
        sop_version: auroraArtifact.sop_version,
        source_artifact_id: auroraArtifact.id,
        created_at: auroraArtifact.created_at,
      },
    ],
    artifacts: [auroraArtifact],
    scope_events: [],
    scope_buffers: [],
    agent_runs: demoDashboard.agent_runs.filter((run) => run.project_id === auroraProject.id),
    warnings: [],
  },
  [northstarProject.id]: {
    generated_at: now,
    project: northstarProject,
    scope_versions: [
      {
        id: "demo-scope-change",
        project_id: northstarProject.id,
        version_number: 2,
        status: "PROPOSED",
        requirements: [
          { requirement_id: "REQ-01", category: "Workflow", description: "Automate the defined operations workflow.", normalized_key: "operations_workflow" },
          { requirement_id: "REQ-02", category: "Dashboard", description: "Provide a simple operations status dashboard.", normalized_key: "operations_dashboard" },
          { requirement_id: "REQ-03", category: "Notification", description: "Notify managers through WhatsApp when approval is needed.", normalized_key: "line_notifications" },
          { requirement_id: "REQ-04", category: "Approval", description: "Allow authorized managers to approve or reject requests from WhatsApp.", normalized_key: "line_approval" },
        ],
        module_selections: northstarArtifact.calculation_inputs,
        assumptions: ["One WhatsApp channel is used for manager notifications."],
        exclusions: ["A WhatsApp mini app and conversational chatbot are excluded."],
        pricing_result: northstarArtifact.pricing_result,
        timeline_result: northstarArtifact.timeline_result,
        total_price_usd: northstarArtifact.pricing_result.total_usd,
        timeline_days: northstarArtifact.timeline_result.total_days,
        currency: "USD",
        sop_version: northstarArtifact.sop_version,
        source_artifact_id: northstarArtifact.id,
        created_at: northstarArtifact.created_at,
      },
      {
        id: "demo-scope-accepted",
        project_id: northstarProject.id,
        version_number: 1,
        status: "ACCEPTED",
        requirements: [
          { requirement_id: "REQ-01", category: "Workflow", description: "Automate the defined operations workflow.", normalized_key: "operations_workflow" },
          { requirement_id: "REQ-02", category: "Dashboard", description: "Provide a simple operations status dashboard.", normalized_key: "operations_dashboard" },
        ],
        module_selections: northstarArtifact.calculation_inputs.slice(0, 2),
        assumptions: ["The dashboard uses standard status tables and filters."],
        exclusions: ["Advanced BI modelling and mobile dashboards are excluded."],
        pricing_result: {
          currency: "USD",
          sop_version: "jvl-demo-v1",
          total_usd: 4750,
          line_items: northstarArtifact.pricing_result.line_items.slice(0, 2),
        },
        timeline_result: { total_days: 5, sop_version: "jvl-demo-v1" },
        total_price_usd: 4750,
        timeline_days: 5,
        currency: "USD",
        sop_version: "jvl-demo-v1",
        source_artifact_id: "demo-artifact-accepted",
        created_at: "2026-08-29T03:30:00Z",
      },
    ],
    artifacts: [northstarArtifact],
    scope_events: demoDashboard.scope_events.filter((event) => event.project_id === northstarProject.id),
    scope_buffers: demoDashboard.scope_buffers.filter((buffer) => buffer.project_id === northstarProject.id),
    agent_runs: demoDashboard.agent_runs.filter((run) => run.project_id === northstarProject.id),
    warnings: [],
  },
};
